### PR TITLE
Point test and build workflow to 2.x instead of main

### PR DESCRIPTION
**Pull request by derek-ho**
### Description
Point test and build workflow to 2.x instead of main 

### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by ps48** [comment]
@derek-ho should this PR point to 2.x branch?

**Review by Swiddis — APPROVED** [review]

**Comment by derek-ho** [comment]
@ps48 it shouldn't matter too much, but 2.x shouldn't be pointing to `main`. I am closing this PR out because it is stale, and I am clearing my open PRs list. @Swiddis @ps48 can you follow up here? It looks like its not failing, but I am concerned that if there is a breaking change in main, we may be building/testing against that on 2.x when we shouldn't be. The easiest way may be to keep it as main for all branches and then do a branch switch if possible - something like: https://github.com/derek-ho/setup-opensearch-dashboards/blob/main/action.yml#L81. @RyanL1997 I got the idea from you.

**Comment by RyanL1997** [comment]
Thanks @derek-ho. Yes, thats a good point to bring up actually. We can also apply this branch switching strategy here I think. We can do that as a follow-up, since we are not having any reusable actions for this repo yet. I would suggest that we can apply this into some re-usable gha.

**Review by RyanL1997 — APPROVED** [review]

**Comment by derek-ho** [comment]
Closing this as we went with the more general way of switching the branch, and 2.10 is stale anyway.

**Pull request closed without merging**
