### PR TITLE
[Bug Fix] Fix the bootstrap failure on the fresh run

### PR DESCRIPTION
**Pull request by RyanL1997**
### Description
Fix the bootstrap failure on the fresh run.

Thanks to @joshuali925 's comment (https://github.com/opensearch-project/dashboards-reporting/issues/263#issuecomment-1883559413). In this PR I have updated the `yarn.lock` file and removed the retries in the current CI workflows.

- Updated the `yarn.lock`
- Removed the retries for dashboards bootstraps for 2 workflows
- Updated the snapshots

### Issues Resolved
* Resolve https://github.com/opensearch-project/dashboards-reporting/issues/263

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by RyanL1997** [comment]
After updating the dependencies, the snapshots tests had some failures https://github.com/opensearch-project/dashboards-reporting/actions/runs/7465626149/job/20315223211?pr=270#step:5:3228. The similar behavior also happened for query-workbench (see [comment](https://github.com/opensearch-project/dashboards-query-workbench/pull/241#issuecomment-1881825731)). I have updated the snapshot by running `yarn test -u`.

**Comment by RyanL1997** [comment]
Right now the previous issue got fixed since the runner can bootstrap the plugin on a fresh run: https://github.com/opensearch-project/dashboards-reporting/actions/runs/7465626033/job/20315215449?pr=270#step:18:18

**Review by joshuali925 — APPROVED** [review]

**Review by ps48 — APPROVED** [review]

**Comment by ps48** [comment]
@RyanL1997 Does this need backport 2.x label?

**Comment by RyanL1997** [comment]
> @RyanL1997 Does this need backport 2.x label? Also, is there no change for package.json file are we directly updating yarn.lock?

Yesterday, I did the version change in #268, so it should be fine to just update the `yarn.lock` here. I will backport them together into 2x btw.

**Pull request merged**
